SystemUI: Fix SystemUI build for kotlin 1.7.0
Kotlin 1.7.0 converts the UNEXPECTED_SAFE_CALL warning into an error:

frameworks/base/packages/SystemUI/src/com/android/systemui/media/MediaDataManager.kt:780:68: error:
type mismatch: inferred type is Boolean? but Boolean was expected
        if (useMediaResumption && removed?.resumeAction != null && removed?.isLocalSession()) {
                                                                   ^

Replace the unnecessary ?. operator.

Bug: 216136346
Test: builds
Change-Id: Ib1605aaff28492b557deac4156f3cc2f4cf8b329
(cherry picked from commit 6e3d0a66d237b143047765ea6041422a567c5c8d)
Merged-In: Ib1605aaff28492b557deac4156f3cc2f4cf8b329